#!/bin/sh
	update-alternatives --remove  passwd /opt/eldk-5.6/armv5te/sysroots/i686-eldk-linux/usr/bin/passwd.shadow
	update-alternatives --remove  chfn /opt/eldk-5.6/armv5te/sysroots/i686-eldk-linux/usr/bin/chfn.shadow
	update-alternatives --remove  newgrp /opt/eldk-5.6/armv5te/sysroots/i686-eldk-linux/usr/bin/newgrp.shadow
	update-alternatives --remove  chsh /opt/eldk-5.6/armv5te/sysroots/i686-eldk-linux/usr/bin/chsh.shadow
	update-alternatives --remove  groups /opt/eldk-5.6/armv5te/sysroots/i686-eldk-linux/usr/bin/groups.shadow
	update-alternatives --remove  chpasswd /opt/eldk-5.6/armv5te/sysroots/i686-eldk-linux/usr/sbin/chpasswd.shadow
	update-alternatives --remove  login /opt/eldk-5.6/armv5te/sysroots/i686-eldk-linux/bin/login.shadow
	update-alternatives --remove  vipw /opt/eldk-5.6/armv5te/sysroots/i686-eldk-linux/sbin/vipw.shadow
	update-alternatives --remove  vigr /opt/eldk-5.6/armv5te/sysroots/i686-eldk-linux/sbin/vigr.shadow
	update-alternatives --remove  su /opt/eldk-5.6/armv5te/sysroots/i686-eldk-linux/bin/su.shadow
